name: docker-build

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - centos.7
          - ubuntu.18.04
    container:
      image: 'docker/Dockerfile.centos.7'
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: test && build
      timeout-minutes: 40
      shell: bash
      run: |
        ./build.sh
